"""fix schemas and env

Revision ID: 97f48ea08bfc
Revises: 28d4d94cae37
Create Date: 2025-06-23 17:20:56.793867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '97f48ea08bfc'
down_revision: Union[str, None] = '28d4d94cae37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed creation of roleenum and adding role column because roleenum is already created in previous migration
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
